project_name: TaskExamples

#################################################################
# Folder structure

project_folder: "./example/data/"

#################################################################
# Repository selection by pattern name

repo_white_pattern:
  - "softwareentwicklung_aufgabe3_sose2021_tutors"
  
repo_black_pattern: ""    # This means empty list

#################################################################
# Content definition
content:
  - Repository
  - Version
  - Issues
  - PullRequests
  - Workflows
  - GitReleases
  - Users

#################################################################

processing_notebooks_folder: ./example/notebooks/

processing_notebooks:
  - P_Preprocessing.ipynb
  - F_TimeStatistics.ipynb
  - F_ProjectOverview.ipynb
  - F_ProjektList.ipynb

#################################################################

feedback_template_file: ./example/feedbackDocument/feedbackTemplate.md
feedback_result_file: ./example/feedbackDocument/result.md