name: UpdateFeedback

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  extract_github_activities:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
             python -m pip install --upgrade pip
             pip install pipenv

      - name: Install dependencies
        run: |
             pipenv install

      - name: Run extraction
        env:
             TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             ./run.sh
