name: UpdateFeedback

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:   
  #  - cron:  '30 5,17 * * *'

jobs:
  extract_github_activities:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
             python -m pip install --upgrade pip
             pip install pipenv

      - name: Install dependencies
        run: |
             pipenv install

      - name: Run extraction
        env:
             ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
             TEST: ${{secrets.TEST}}
        run: |
             pipenv run python3 -m github2pandas_manager -path ./example/config.yml
             pipenv run python3 -m FeedbackGeneration -path ./example/config.yml
             mv ./example/feedbackDocument/result.md README.md

      - name: Commit files
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add README.md
             git add ./example/notebooks/F_TimeStatistics.png
             git commit -m "Add new statistics" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.ACCESS_TOKEN }}
             branch: main
             
