name: UpdateFeedback

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:   
    - cron:  '30 5,17 * * *'

jobs:
  extract_github_activities:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
             python -m pip install --upgrade pip
             pip install pipenv

      - name: Install dependencies
        run: |
             pipenv install

      - name: Run extraction
        env:
             EXT_TOKEN: ${{ secrets.EXT_TOKEN }}
        run: |
             ./run.sh

      - name: Commit files
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add README.md
             git add ./images/heatmap.png
             git commit -m "Add new statistics" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.EXT_TOKEN }}
             branch: main
             
